import { KEYS_ENUM } from "../constants/herarichy.constants";

export const organizationsData = {
  [KEYS_ENUM.TECH_CORP]: [
    {
      name: "Engineering",
      node: KEYS_ENUM.DEPARTMENT,
      children: [
        {
          name: "Web Development",
          node: KEYS_ENUM.SUB_DEPARTMENT,
          children: [
            {
              name: "Frontend",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Alice Johnson",
                  email: "alice@techcorp.com",
                  phone: "123-456-7890",
                  city: "New York",
                  address: "123 Tech Street, NY 10001",
                },
                {
                  name: "Bob Smith",
                  email: "bob@techcorp.com",
                  phone: "123-456-7891",
                  city: "San Francisco",
                  address: "456 Code Avenue, CA 94105",
                },
                {
                  name: "Charlie Brown",
                  email: "charlie@techcorp.com",
                  phone: "123-456-7892",
                  city: "Los Angeles",
                  address: "789 Main Street, CA 90001",
                },
                {
                  name: "Diana Prince",
                  email: "diana@techcorp.com",
                  phone: "123-456-7893",
                  city: "Chicago",
                  address: "1011 Oak Avenue, IL 60601",
                },
              ],
            },
            {
              name: "Backend",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Eve Williams",
                  email: "eve@techcorp.com",
                  phone: "123-456-7894",
                  city: "Houston",
                  address: "1213 Pine Street, TX 77001",
                },
                {
                  name: "Frank Miller",
                  email: "frank@techcorp.com",
                  phone: "123-456-7895",
                  city: "Phoenix",
                  address: "1415 Maple Drive, AZ 85001",
                },
                {
                  name: "Grace Lee",
                  email: "grace@techcorp.com",
                  phone: "123-456-7896",
                  city: "Philadelphia",
                  address: "1617 Birch Lane, PA 19101",
                },
                {
                  name: "Henry Ford",
                  email: "henry@techcorp.com",
                  phone: "123-456-7897",
                  city: "San Antonio",
                  address: "1819 Willow Street, TX 78201",
                },
              ],
            },
            {
              name: "DevOps",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Irene Adler",
                  email: "irene@techcorp.com",
                  phone: "123-456-7898",
                  city: "San Diego",
                  address: "2021 Cedar Avenue, CA 92101",
                },
                {
                  name: "Jack Sparrow",
                  email: "jack@techcorp.com",
                  phone: "123-456-7899",
                  city: "Dallas",
                  address: "2223 Oak Street, TX 75201",
                },
                {
                  name: "Kate Austen",
                  email: "kate@techcorp.com",
                  phone: "123-456-7900",
                  city: "San Jose",
                  address: "2425 Elm Street, CA 95101",
                },
                {
                  name: "Liam Neeson",
                  email: "liam@techcorp.com",
                  phone: "123-456-7901",
                  city: "Austin",
                  address: "2627 Pine Avenue, TX 78701",
                },
              ],
            },
          ],
        },
        {
          name: "Mobile App Development",
          node: KEYS_ENUM.SUB_DEPARTMENT,
          children: [
            {
              name: "Android",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Alice Johnson",
                  email: "alice@techcorp.com",
                  phone: "123-456-7890",
                  city: "New York",
                  address: "123 Tech Street, NY 10001",
                },
                {
                  name: "Bob Smith",
                  email: "bob@techcorp.com",
                  phone: "123-456-7891",
                  city: "San Francisco",
                  address: "456 Code Avenue, CA 94105",
                },
                {
                  name: "Charlie Brown",
                  email: "charlie@techcorp.com",
                  phone: "123-456-7892",
                  city: "Los Angeles",
                  address: "789 Main Street, CA 90001",
                },
                {
                  name: "Diana Prince",
                  email: "diana@techcorp.com",
                  phone: "123-456-7893",
                  city: "Chicago",
                  address: "1011 Oak Avenue, IL 60601",
                },
              ],
            },
            {
              name: "IOS",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Eve Williams",
                  email: "eve@techcorp.com",
                  phone: "123-456-7894",
                  city: "Houston",
                  address: "1213 Pine Street, TX 77001",
                },
                {
                  name: "Frank Miller",
                  email: "frank@techcorp.com",
                  phone: "123-456-7895",
                  city: "Phoenix",
                  address: "1415 Maple Drive, AZ 85001",
                },
                {
                  name: "Grace Lee",
                  email: "grace@techcorp.com",
                  phone: "123-456-7896",
                  city: "Philadelphia",
                  address: "1617 Birch Lane, PA 19101",
                },
                {
                  name: "Henry Ford",
                  email: "henry@techcorp.com",
                  phone: "123-456-7897",
                  city: "San Antonio",
                  address: "1819 Willow Street, TX 78201",
                },
              ],
            },
            {
              name: "DevOps",
              node: KEYS_ENUM.TEAM,
              children: [
                {
                  name: "Irene Adler",
                  email: "irene@techcorp.com",
                  phone: "123-456-7898",
                  city: "San Diego",
                  address: "2021 Cedar Avenue, CA 92101",
                },
                {
                  name: "Jack Sparrow",
                  email: "jack@techcorp.com",
                  phone: "123-456-7899",
                  city: "Dallas",
                  address: "2223 Oak Street, TX 75201",
                },
                {
                  name: "Kate Austen",
                  email: "kate@techcorp.com",
                  phone: "123-456-7900",
                  city: "San Jose",
                  address: "2425 Elm Street, CA 95101",
                },
                {
                  name: "Liam Neeson",
                  email: "liam@techcorp.com",
                  phone: "123-456-7901",
                  city: "Austin",
                  address: "2627 Pine Avenue, TX 78701",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "Marketing",
      node: KEYS_ENUM.DEPARTMENT,
      children: [
        {
          name: "Digital",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Mia Wallace",
              email: "mia@techcorp.com",
              phone: "123-456-7902",
              city: "Seattle",
              address: "2829 Birch Street, WA 98101",
            },
            {
              name: "Neo Anderson",
              email: "neo@techcorp.com",
              phone: "123-456-7903",
              city: "Denver",
              address: "3031 Maple Drive, CO 80201",
            },
            {
              name: "Olivia Pope",
              email: "olivia@techcorp.com",
              phone: "123-456-7904",
              city: "Washington",
              address: "3233 Oak Avenue, DC 20001",
            },
            {
              name: "Peter Parker",
              email: "peter@techcorp.com",
              phone: "123-456-7905",
              city: "Boston",
              address: "3435 Pine Street, MA 02101",
            },
          ],
        },
        {
          name: "Brand",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Quinn Fabray",
              email: "quinn@techcorp.com",
              phone: "123-456-7906",
              city: "Detroit",
              address: "3637 Willow Street, MI 48201",
            },
            {
              name: "Rachel Green",
              email: "rachel@techcorp.com",
              phone: "123-456-7907",
              city: "Jacksonville",
              address: "3839 Cedar Avenue, FL 32201",
            },
            {
              name: "Sherlock Holmes",
              email: "sherlock@techcorp.com",
              phone: "123-456-7908",
              city: "Indianapolis",
              address: "4041 Elm Street, IN 46201",
            },
            {
              name: "Tony Stark",
              email: "tony@techcorp.com",
              phone: "123-456-7909",
              city: "Columbus",
              address: "4243 Pine Avenue, OH 43201",
            },
          ],
        },
        {
          name: "Content",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Uma Thurman",
              email: "uma@techcorp.com",
              phone: "123-456-7910",
              city: "Fort Worth",
              address: "4445 Birch Street, TX 76101",
            },
            {
              name: "Victor Frankenstein",
              email: "victor@techcorp.com",
              phone: "123-456-7911",
              city: "Charlotte",
              address: "4647 Maple Drive, NC 28201",
            },
            {
              name: "Walter White",
              email: "walter@techcorp.com",
              phone: "123-456-7912",
              city: "Baltimore",
              address: "4849 Oak Avenue, MD 21201",
            },
            {
              name: "Xena Warrior",
              email: "xena@techcorp.com",
              phone: "123-456-7913",
              city: "Milwaukee",
              address: "5051 Pine Street, WI 53201",
            },
          ],
        },
      ],
    },
  ],
  [KEYS_ENUM.FINANCE_HUB]: [
    {
      name: "Accounting",
      node: KEYS_ENUM.DEPARTMENT,
      children: [
        {
          name: "Payroll",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Yoda Master",
              email: "yoda@financehub.com",
              phone: "234-567-8901",
              city: "New York",
              address: "123 Wall Street, NY 10005",
            },
            {
              name: "Zelda Link",
              email: "zelda@financehub.com",
              phone: "234-567-8902",
              city: "San Francisco",
              address: "456 Market Street, CA 94104",
            },
            {
              name: "Adam Sandler",
              email: "adam@financehub.com",
              phone: "234-567-8903",
              city: "Los Angeles",
              address: "789 Hollywood Blvd, CA 90028",
            },
            {
              name: "Bella Swan",
              email: "bella@financehub.com",
              phone: "234-567-8904",
              city: "Seattle",
              address: "1011 Pike Street, WA 98101",
            },
          ],
        },
        {
          name: "Audit",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Celine Dion",
              email: "celine@financehub.com",
              phone: "234-567-8905",
              city: "Las Vegas",
              address: "1213 Las Vegas Blvd, NV 89109",
            },
            {
              name: "David Bowie",
              email: "david@financehub.com",
              phone: "234-567-8906",
              city: "London",
              address: "1415 Oxford Street, London, UK",
            },
            {
              name: "Emma Watson",
              email: "emma@financehub.com",
              phone: "234-567-8907",
              city: "Paris",
              address: "1617 Champs-Élysées, Paris, France",
            },
            {
              name: "Freddie Mercury",
              email: "freddie@financehub.com",
              phone: "234-567-8908",
              city: "London",
              address: "1819 Piccadilly, London, UK",
            },
          ],
        },
        {
          name: "Tax",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Gal Gadot",
              email: "gal@financehub.com",
              phone: "234-567-8909",
              city: "Tel Aviv",
              address: "2021 Rothschild Blvd, Tel Aviv, Israel",
            },
            {
              name: "Hugh Jackman",
              email: "hugh@financehub.com",
              phone: "234-567-8910",
              city: "Sydney",
              address: "2223 George Street, Sydney, Australia",
            },
            {
              name: "Idris Elba",
              email: "idris@financehub.com",
              phone: "234-567-8911",
              city: "London",
              address: "2425 Regent Street, London, UK",
            },
            {
              name: "Jennifer Lawrence",
              email: "jennifer@financehub.com",
              phone: "234-567-8912",
              city: "Louisville",
              address: "2627 Main Street, KY 40202",
            },
          ],
        },
      ],
    },
    {
      name: "Investment",
      node: KEYS_ENUM.DEPARTMENT,
      children: [
        {
          name: "Stocks",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Keanu Reeves",
              email: "keanu@financehub.com",
              phone: "234-567-8913",
              city: "New York",
              address: "2829 Wall Street, NY 10005",
            },
            {
              name: "Leonardo DiCaprio",
              email: "leonardo@financehub.com",
              phone: "234-567-8914",
              city: "Los Angeles",
              address: "3031 Hollywood Blvd, CA 90028",
            },
            {
              name: "Meryl Streep",
              email: "meryl@financehub.com",
              phone: "234-567-8915",
              city: "New York",
              address: "3233 Fifth Avenue, NY 10022",
            },
            {
              name: "Natalie Portman",
              email: "natalie@financehub.com",
              phone: "234-567-8916",
              city: "Jerusalem",
              address: "3435 King David Street, Jerusalem, Israel",
            },
          ],
        },
        {
          name: "Bonds",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Orlando Bloom",
              email: "orlando@financehub.com",
              phone: "234-567-8917",
              city: "London",
              address: "3637 Bond Street, London, UK",
            },
            {
              name: "Penelope Cruz",
              email: "penelope@financehub.com",
              phone: "234-567-8918",
              city: "Madrid",
              address: "3839 Gran Vía, Madrid, Spain",
            },
            {
              name: "Quentin Tarantino",
              email: "quentin@financehub.com",
              phone: "234-567-8919",
              city: "Los Angeles",
              address: "4041 Sunset Blvd, CA 90028",
            },
            {
              name: "Ryan Reynolds",
              email: "ryan@financehub.com",
              phone: "234-567-8920",
              city: "Vancouver",
              address: "4243 Granville Street, Vancouver, Canada",
            },
          ],
        },
        {
          name: "Crypto",
          node: KEYS_ENUM.TEAM,
          children: [
            {
              name: "Scarlett Johansson",
              email: "scarlett@financehub.com",
              phone: "234-567-8921",
              city: "New York",
              address: "4445 Broadway, NY 10003",
            },
            {
              name: "Tom Hanks",
              email: "tom@financehub.com",
              phone: "234-567-8922",
              city: "Los Angeles",
              address: "4647 Mulholland Drive, CA 90077",
            },
            {
              name: "Uma Thurman",
              email: "uma@financehub.com",
              phone: "234-567-8923",
              city: "New York",
              address: "4849 Central Park West, NY 10024",
            },
            {
              name: "Vin Diesel",
              email: "vin@financehub.com",
              phone: "234-567-8924",
              city: "Los Angeles",
              address: "5051 Wilshire Blvd, CA 90036",
            },
          ],
        },
      ],
    },
  ],
  // {
  //   name: "HealthCare Inc",
  //   children: [
  //     {
  //       name: "Research",
  //       teams: [
  //         {
  //           name: "Clinical Trials",
  //           employees: [
  //             {
  //               name: "Will Smith",
  //               email: "will@healthcare.com",
  //               phone: "345-678-9012",
  //               city: "Philadelphia",
  //               address: "123 Medical Drive, PA 19103",
  //             },
  //             {
  //               name: "Xavier Charles",
  //               email: "xavier@healthcare.com",
  //               phone: "345-678-9013",
  //               city: "Boston",
  //               address: "456 Hospital Lane, MA 02115",
  //             },
  //             {
  //               name: "Yvonne Strahovski",
  //               email: "yvonne@healthcare.com",
  //               phone: "345-678-9014",
  //               city: "New York",
  //               address: "789 Clinic Street, NY 10016",
  //             },
  //             {
  //               name: "Zoe Saldana",
  //               email: "zoe@healthcare.com",
  //               phone: "345-678-9015",
  //               city: "Los Angeles",
  //               address: "1011 Health Way, CA 90045",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Drug Development",
  //           employees: [
  //             {
  //               name: "Aaron Paul",
  //               email: "aaron@healthcare.com",
  //               phone: "345-678-9016",
  //               city: "Albuquerque",
  //               address: "1213 Research Road, NM 87106",
  //             },
  //             {
  //               name: "Bryan Cranston",
  //               email: "bryan@healthcare.com",
  //               phone: "345-678-9017",
  //               city: "Los Angeles",
  //               address: "1415 Lab Lane, CA 90024",
  //             },
  //             {
  //               name: "Chadwick Boseman",
  //               email: "chadwick@healthcare.com",
  //               phone: "345-678-9018",
  //               city: "Anderson",
  //               address: "1617 Science Drive, SC 29621",
  //             },
  //             {
  //               name: "Daisy Ridley",
  //               email: "daisy@healthcare.com",
  //               phone: "345-678-9019",
  //               city: "London",
  //               address: "1819 Pharmacy Street, London, UK",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Biotech",
  //           employees: [
  //             {
  //               name: "Emilia Clarke",
  //               email: "emilia@healthcare.com",
  //               phone: "345-678-9020",
  //               city: "London",
  //               address: "2021 Biotech Blvd, London, UK",
  //             },
  //             {
  //               name: "Finn Wolfhard",
  //               email: "finn@healthcare.com",
  //               phone: "345-678-9021",
  //               city: "Vancouver",
  //               address: "2223 Science Way, Vancouver, Canada",
  //             },
  //             {
  //               name: "Gal Gadot",
  //               email: "gal@healthcare.com",
  //               phone: "345-678-9022",
  //               city: "Tel Aviv",
  //               address: "2425 Medical Center, Tel Aviv, Israel",
  //             },
  //             {
  //               name: "Henry Cavill",
  //               email: "henry@healthcare.com",
  //               phone: "345-678-9023",
  //               city: "Jersey",
  //               address: "2627 Health Lane, Jersey, UK",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       name: "Patient Care",
  //       teams: [
  //         {
  //           name: "Emergency",
  //           employees: [
  //             {
  //               name: "Isla Fisher",
  //               email: "isla@healthcare.com",
  //               phone: "345-678-9024",
  //               city: "Sydney",
  //               address: "2829 ER Drive, Sydney, Australia",
  //             },
  //             {
  //               name: "Jason Momoa",
  //               email: "jason@healthcare.com",
  //               phone: "345-678-9025",
  //               city: "Honolulu",
  //               address: "3031 Emergency Lane, HI 96813",
  //             },
  //             {
  //               name: "Karen Gillan",
  //               email: "karen@healthcare.com",
  //               phone: "345-678-9026",
  //               city: "Inverness",
  //               address: "3233 Hospital Road, Inverness, Scotland",
  //             },
  //             {
  //               name: "Liam Hemsworth",
  //               email: "liam@healthcare.com",
  //               phone: "345-678-9027",
  //               city: "Melbourne",
  //               address: "3435 Medical Center, Melbourne, Australia",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Intensive Care",
  //           employees: [
  //             {
  //               name: "Margot Robbie",
  //               email: "margot@healthcare.com",
  //               phone: "345-678-9028",
  //               city: "Melbourne",
  //               address: "3637 ICU Drive, Melbourne, Australia",
  //             },
  //             {
  //               name: "Nikolaj Coster-Waldau",
  //               email: "nikolaj@healthcare.com",
  //               phone: "345-678-9029",
  //               city: "Copenhagen",
  //               address: "3839 Hospital Lane, Copenhagen, Denmark",
  //             },
  //             {
  //               name: "Oscar Isaac",
  //               email: "oscar@healthcare.com",
  //               phone: "345-678-9030",
  //               city: "Guatemala City",
  //               address: "4041 Medical Center, Guatemala City, Guatemala",
  //             },
  //             {
  //               name: "Pedro Pascal",
  //               email: "pedro@healthcare.com",
  //               phone: "345-678-9031",
  //               city: "Santiago",
  //               address: "4243 Health Way, Santiago, Chile",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Outpatient",
  //           employees: [
  //             {
  //               name: "Queen Latifah",
  //               email: "queen@healthcare.com",
  //               phone: "345-678-9032",
  //               city: "Newark",
  //               address: "4445 Outpatient Drive, NJ 07102",
  //             },
  //             {
  //               name: "Robert Downey Jr.",
  //               email: "robert@healthcare.com",
  //               phone: "345-678-9033",
  //               city: "New York",
  //               address: "4647 Clinic Street, NY 10016",
  //             },
  //             {
  //               name: "Sophie Turner",
  //               email: "sophie@healthcare.com",
  //               phone: "345-678-9034",
  //               city: "London",
  //               address: "4849 Hospital Road, London, UK",
  //             },
  //             {
  //               name: "Timothée Chalamet",
  //               email: "timothee@healthcare.com",
  //               phone: "345-678-9035",
  //               city: "New York",
  //               address: "5051 Health Way, NY 10023",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   name: "EduTech Solutions",
  //   children: [
  //     {
  //       name: "Course Development",
  //       teams: [
  //         {
  //           name: "Math",
  //           employees: [
  //             {
  //               name: "Uma Thurman",
  //               email: "uma@edutech.com",
  //               phone: "456-789-0123",
  //               city: "New York",
  //               address: "123 Math Street, NY 10001",
  //             },
  //             {
  //               name: "Viggo Mortensen",
  //               email: "viggo@edutech.com",
  //               phone: "456-789-0124",
  //               city: "Los Angeles",
  //               address: "456 Algebra Avenue, CA 90001",
  //             },
  //             {
  //               name: "Winona Ryder",
  //               email: "winona@edutech.com",
  //               phone: "456-789-0125",
  //               city: "Chicago",
  //               address: "789 Calculus Court, IL 60601",
  //             },
  //             {
  //               name: "Xander Berkeley",
  //               email: "xander@edutech.com",
  //               phone: "456-789-0126",
  //               city: "San Francisco",
  //               address: "1011 Geometry Lane, CA 94101",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Science",
  //           employees: [
  //             {
  //               name: "Yara Shahidi",
  //               email: "yara@edutech.com",
  //               phone: "456-789-0127",
  //               city: "Los Angeles",
  //               address: "1213 Biology Blvd, CA 90001",
  //             },
  //             {
  //               name: "Zendaya",
  //               email: "zendaya@edutech.com",
  //               phone: "456-789-0128",
  //               city: "Oakland",
  //               address: "1415 Chemistry Court, CA 94601",
  //             },
  //             {
  //               name: "Andrew Garfield",
  //               email: "andrew@edutech.com",
  //               phone: "456-789-0129",
  //               city: "New York",
  //               address: "1617 Physics Place, NY 10001",
  //             },
  //             {
  //               name: "Brie Larson",
  //               email: "brie@edutech.com",
  //               phone: "456-789-0130",
  //               city: "Los Angeles",
  //               address: "1819 Astronomy Avenue, CA 90001",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Languages",
  //           employees: [
  //             {
  //               name: "Chris Hemsworth",
  //               email: "chris@edutech.com",
  //               phone: "456-789-0131",
  //               city: "Sydney",
  //               address: "2021 Spanish Street, Sydney, Australia",
  //             },
  //             {
  //               name: "Daisy Edgar-Jones",
  //               email: "daisy@edutech.com",
  //               phone: "456-789-0132",
  //               city: "London",
  //               address: "2223 French Avenue, London, UK",
  //             },
  //             {
  //               name: "Eddie Redmayne",
  //               email: "eddie@edutech.com",
  //               phone: "456-789-0133",
  //               city: "London",
  //               address: "2425 German Lane, London, UK",
  //             },
  //             {
  //               name: "Florence Pugh",
  //               email: "florence@edutech.com",
  //               phone: "456-789-0134",
  //               city: "Oxford",
  //               address: "2627 Italian Court, Oxford, UK",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       name: "Technology",
  //       teams: [
  //         {
  //           name: "LMS Development",
  //           employees: [
  //             {
  //               name: "George Clooney",
  //               email: "george@edutech.com",
  //               phone: "456-789-0135",
  //               city: "Los Angeles",
  //               address: "2829 Tech Street, CA 90001",
  //             },
  //             {
  //               name: "Hailee Steinfeld",
  //               email: "hailee@edutech.com",
  //               phone: "456-789-0136",
  //               city: "Los Angeles",
  //               address: "3031 Code Avenue, CA 90001",
  //             },
  //             {
  //               name: "Ian McKellen",
  //               email: "ian@edutech.com",
  //               phone: "456-789-0137",
  //               city: "London",
  //               address: "3233 Software Lane, London, UK",
  //             },
  //             {
  //               name: "Jessica Chastain",
  //               email: "jessica@edutech.com",
  //               phone: "456-789-0138",
  //               city: "Sacramento",
  //               address: "3435 Development Drive, CA 95814",
  //             },
  //           ],
  //         },
  //         {
  //           name: "Mobile Apps",
  //           employees: [
  //             {
  //               name: "Kit Harington",
  //               email: "kit@edutech.com",
  //               phone: "456-789-0139",
  //               city: "London",
  //               address: "3637 App Street, London, UK",
  //             },
  //             {
  //               name: "Lupita Nyong'o",
  //               email: "lupita@edutech.com",
  //               phone: "456-789-0140",
  //               city: "Nairobi",
  //               address: "3839 Mobile Lane, Nairobi, Kenya",
  //             },
  //             {
  //               name: "Maisie Williams",
  //               email: "maisie@edutech.com",
  //               phone: "456-789-0141",
  //               city: "London",
  //               address: "4041 IOS Avenue, London, UK",
  //             },
  //             {
  //               name: "Naomi Scott",
  //               email: "naomi@edutech.com",
  //               phone: "456-789-0142",
  //               city: "London",
  //               address: "4243 Android Court, London, UK",
  //             },
  //           ],
  //         },
  //         {
  //           name: "AI Integration",
  //           employees: [
  //             {
  //               name: "Olivia Colman",
  //               email: "olivia@edutech.com",
  //               phone: "456-789-0143",
  //               city: "London",
  //               address: "4445 AI Street, London, UK",
  //             },
  //             {
  //               name: "Paul Rudd",
  //               email: "paul@edutech.com",
  //               phone: "456-789-0144",
  //               city: "New York",
  //               address: "4647 Machine Learning Lane, NY 10001",
  //             },
  //             {
  //               name: "Quvenzhané Wallis",
  //               email: "quvenzhane@edutech.com",
  //               phone: "456-789-0145",
  //               city: "Houston",
  //               address: "4849 Deep Learning Drive, TX 77001",
  //             },
  //             {
  //               name: "Rami Malek",
  //               email: "rami@edutech.com",
  //               phone: "456-789-0146",
  //               city: "Los Angeles",
  //               address: "5051 Neural Network Avenue, CA 90001",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
};

export const organizations = [
  { label: "TechCorp", value: KEYS_ENUM.TECH_CORP },
  { label: "FinanceHub", value: KEYS_ENUM.FINANCE_HUB },
  // { label: "HealthCare Inc", value: KEYS_ENUM.HEALTH_CARE },
  // { label: "EduTech Solutions", value: KEYS_ENUM.EDUTECH_SOLUTION },
];
